# Generated by Django 3.2.7 on 2021-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('company_list', models.FileField(blank=True, null=True, upload_to='InputFiles', verbose_name='')),
                ('company_name', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
